name: PatrickOKeeffe
favicon: null
layout_spectrum: 0.98523
typography_spectrum: 0.74191
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-72359853-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f5dfc7'
    - '#5f4f3f'
    - '#c0a588'
    - '#83715d'
    - '#3f2f1f'
  brandStrength: 0.7141841663978994
  lightness: 0.26330683496780694
  saturation: 0.5835312833078206
  rhythmicContrast: 0.855183677515015
purpose: []
